import sqlalchemy

"""
[
lista y listaTCA: Usado para subir paquetes de vuelta sintys.
namesList y dtypeDictCSV: Usado para dar titulo y tipos de dato a la lectura SOMOSO.
dtypeDictSQL: Los tipos de dato para subir el dataframe a la DB.
dtypeDictNomsXLS: Dar tipo a las columnas del excel a leer paar el cruce NOMS.
]
"""
# Listas para paquete 3
lista = [
    {
        "Nombre": "B00",
        "dtype": {
            "id_persona ": str,
            " QID  ": str,
            " BASE  ": str,
            " CORTE  ": str,
            " CUIT  ": str,
            " TDOC  ": str,
            " NDOC  ": str,
            " SEXO  ": str,
            " DENO  ": str,
            " FNAC  ": str,
            " MONTO  ": str,
            " PROV  ": str,
            " PERIODO  ": str,
            " PERIODO_BASE  ": str,
            " PERIODO_ACT  ": str,
            " BASE_PROV  ": str,
            " PASAPORTE  ": str,
            " APELLIDO_ORIG  ": str,
            " NOMBRE_ORIG  ": str,
            " NDOC_ORIG  ": str,
            " CUIT_ORIG  ": str,
            " FNAC_ORIG  ": str,
            " SEXO_ORIGEN  ": str,
            " PROV_ORIG  ": str,
            " MUNICIPIO  ": str,
            " NACIONALIDAD ": str,
        },
    },
    {
        "Nombre": "DATOS",
        "dtype": {
            "id_persona": str,
            "cuit": str,
            "tdoc": str,
            "ndoc": str,
            "deno": str,
            "sexo": str,
            "fnac": str,
            "grado_confiab": str,
        },
    },
    {
        "Nombre": "EMBARCACIONES",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": str,
            "PERIODO_BASE": str,
            "MATRICULA": str,
        },
    },
    {
        "Nombre": "AERONAVES",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": str,
            "PERIODO_BASE": str,
            "MATRICULA": str,
        },
    },
    {
        "Nombre": "EMPLEO_DEPENDIENTE",
        "dtype": {
            "ID_PERSONA": str,
            "SECTOR": str,
            "TIPO_EMPLEO_PUBLICO": str,
            "BASE": str,
            "SITUACION_LABORAL": str,
            "PERIODO_BASE": str,
            "MONTO": str,
            "CUIT_EMPLEADOR": str,
            "DENO_EMPLEADOR": str,
        },
    },
    {
        "Nombre": "EMPLEO_INDEPENDIENTE",
        "dtype": {"ID_PERSONA": str, "BASE": str, "PERIODO_BASE": str},
    },
    {
        "Nombre": "FALLECIDOS",
        "dtype": {
            "ID_PERSONA": str,
            "ANIO": str,
            "ACTA": str,
            "TOMO": str,
            "FOLIO": str,
            "SECCIONAL": str,
            "FFALL": str,
            "ANOACTA": str,
            "IMAGEN_TIFF": str,
            "BASE": str,
        },
    },
    {
        "Nombre": "INMUEBLES",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": str,
            "PERIODO_BASE": str,
            "DOMICILIO_FISCAL": str,
            "CALLE": str,
            "NUMERO": str,
            "PISO": str,
            "APARTAMENTO": str,
            "COD_POSTAL": str,
            "LOCALIDAD": str,
            "DEPARTAMENTO": str,
            "PROVINCIA": str,
            "NC_NOMENCLATURA": str,
            "NC_PARTIDO": str,
            "NC_DEPARTAMENTO": str,
            "NC_DISTRITO": str,
            "NC_CIRCUNSCRIPCION": str,
            "NC_SECCION": str,
            "NC_FRACCION": str,
            "NC_MANZANA": str,
            "NC_PARCELA": str,
            "NC_CHACRA": str,
            "NC_QUINTA": str,
            "NC_LOTE": str,
            "NC_UNIC_FUNCIONAL": str,
            "FECHA_INSCRIPCION": str,
            "PARTIDA": str,
            "MATRICULA": str,
        },
    },
    {
        "Nombre": "JUBILACIONES_PENSIONES",
        "dtype": {
            "ID_PERSONA": str,
            "TBENE": str,
            "BASE": str,
            "PERIODO_BASE": str,
            "LEY_APLICADA": str,
            "MONTO": str,
            "DESC_BENE": str,
        },
    },
    {
        "Nombre": "PADRON_AUTOMOTORES",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": str,
            "PERIODO_BASE": str,
            "PROVINCIA": str,
            "DOMINIO": str,
            "FECHA_TITU_DESDE": str,
            "CALLE": str,
            "NUMERO": str,
            "PISO": str,
            "DEPTO": str,
            "COD_POSTAL": str,
            "LOCALIDAD": str,
            "MODELO": str,
            "FECHA_INSCRIPCION": str,
            "USO_VEHICULO": str,
            "TIPO_AUTOMOTOR_NAC": str,
            "TIPO_AUTOMOTOR_IMP": str,
        },
    },
    {
        "Nombre": "PERSONAS_JURIDICAS",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": str,
            "PERIODO_BASE": str,
            "PROVINCIA": str,
            "FECHA_INGRESO": str,
            "FECHA_EGRESO": str,
            "DOMICILIO_ACC": str,
            "CALLE_ACC": str,
            "NUMERO_ACC": str,
            "PISO_ACC": str,
            "DEPTO_ACC": str,
            "COD_POST_ACC": str,
            "LOCALIDAD_ACC": str,
            "COD_LOC_ACC": str,
            "DEPARTAMENTO_ACC": str,
            "COD_DEPARTAMENTO_ACC": str,
            "TIPO_SOC": str,
            "DENO_SOC": str,
            "CUIT_SOC": str,
            "DOMICILIO_SOC": str,
            "CALLE_SOC": str,
            "NUMERO_SOC": str,
            "PISO_SOC": str,
            "DEPTO_SOC": str,
            "COD_POST_SOC": str,
            "LOCALIDAD_SOC": str,
            "COD_LOCALIDAD_SOC": str,
            "DEPARTAMENTO_SOC": str,
            "COD_DEPARTAMENTO_SOC": str,
            "PROVINCIA_SOC": str,
            "FECHA_CONSTITUCION": str,
            "NRO_LEGAJO": str,
        },
    },
    {
        "Nombre": "PNC",
        "dtype": {
            "ID_PERSONA": str,
            "TBENE": str,
            "BASE": str,
            "PERIODO_BASE": str,
            "MONTO": str,
        },
    },
]

listaTCA = [
    {"Nombre": "TCA_100", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_200", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_302", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5249", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5375", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5396", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5397", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5399", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5411", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5453", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5493", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5550", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
]
# SOMOSO 1.0 - namesList , dtypeDictCSV, dtypeDictSQL
namesList = [
    "IdSolicitud",
    "IdTipoSolicitud",
    "CUIL",
    "CUILViejo",
    "apeYnom",
    "Apellidos",
    "Nombres",
    "FechaNacimiento",
    "IdPaisNacimiento",
    "Sexo",
    "Edad",
    "Telefono",
    "Email",
    "FechaUltAct",
    "Dependencia",
    "IdPrograma",
    "IdTipoEfector",
    "NombreAgrupamiento",
    "Matricula",
    "IdActividad",
    "NumeroRenaf",
    "IdCentroEducativo",
    "IdNivelEducativo",
    "NivelFinalizado",
    "UltimoAnioAprobado",
    "IdCoberturaSalud",
    "IdAccesoSalud",
    "IdDificultadSalud",
    "IdObraSocial",
    "IdTrabajoSemanaAnterior",
    "TrabajoInformalSemanaAnterior",
    "BuscoTrabajoUltimos30Dias",
    "IdTiempoBuscaTrabajo",
    "TrabajoAlgunaVez",
    "IdTrabajoInformal",
    "NombreTrabajoInformal",
    "IdIngresosEfector",
    "Ingresos",
    "ComparteViviendaGrupoFamiliar",
    "IdTipoVivienda",
    "TipoViviendaOtro",
    "IdMaterialPisoVivienda",
    "IdMaterialTechoVivienda",
    "AmbientesVivienda",
    "IdAguaProvieneVivienda",
    "IdAguaLlegaVivienda",
    "IdBanioVivienda",
    "IdDesagueVivienda",
    "ZonaInundableVivienda",
    "BasuralesVivienda",
    "AlumbradoPublicoVivienda",
    "PavimentoVivienda",
    "RecoleccionResiduosVivienda",
    "TransportePublicoVivienda",
    "IdProvincia",
    "Provincia",
    "domLocalidad",
    "domCalle",
    "domCalleAltura",
    "domPiso",
    "domDto",
    "domMunicipio",
    "domCodigoPostal",
    "IdMotivoRenuncia",
    "FechaFallecimiento",
    "MotivoOtro",
    "ADH_CUIL",
    "ADH_apeyNom",
    "ADH_Apellidos",
    "ADH_Nombres",
    "ADH_AdhiereObraSocial",
    "ADH_DatosAdp",
    "ADH_FechaNacimiento",
    "ADH_Sexo",
    "ADH_Edad",
    "ADH_IdCentroEducativo",
    "ADH_IdNivelEducativo",
    "ADH_NivelFinalizado",
    "ADH_ultimoAnioAprobado",
    "ADH_IngresoUltimos30Dias",
    "ADH_Ingresos",
    "ADH_IdParentesco",
]

dtypeDictCSV = {
    "IdSolicitud": str,
    "IdTipoSolicitud": str,
    "CUIL": str,
    "CUILViejo": str,
    "apeYnom": str,
    "Apellidos": str,
    "Nombres": str,
    "FechaNacimiento": str,
    "IdPaisNacimiento": str,
    "Sexo": str,
    "Edad": str,
    "Telefono": str,
    "Email": str,
    "FechaUltAct": str,
    "Dependencia": str,
    "IdPrograma": str,
    "IdTipoEfector": str,
    "NombreAgrupamiento": str,
    "Matricula": str,
    "IdActividad": str,
    "NumeroRenaf": str,
    "IdCentroEducativo": str,
    "IdNivelEducativo": str,
    "NivelFinalizado": str,
    "UltimoAnioAprobado": str,
    "IdCoberturaSalud": str,
    "IdAccesoSalud": str,
    "IdDificultadSalud": str,
    "IdObraSocial": str,
    "IdTrabajoSemanaAnterior": str,
    "TrabajoInformalSemanaAnterior": str,
    "BuscoTrabajoUltimos30Dias": str,
    "IdTiempoBuscaTrabajo": str,
    "TrabajoAlgunaVez": str,
    "IdTrabajoInformal": str,
    "NombreTrabajoInformal": str,
    "IdIngresosEfector": str,
    "Ingresos": str,
    "ComparteViviendaGrupoFamiliar": str,
    "IdTipoVivienda": str,
    "TipoViviendaOtro": str,
    "IdMaterialPisoVivienda": str,
    "IdMaterialTechoVivienda": str,
    "AmbientesVivienda": str,
    "IdAguaProvieneVivienda": str,
    "IdAguaLlegaVivienda": str,
    "IdBanioVivienda": str,
    "IdDesagueVivienda": str,
    "ZonaInundableVivienda": str,
    "BasuralesVivienda": str,
    "AlumbradoPublicoVivienda": str,
    "PavimentoVivienda": str,
    "RecoleccionResiduosVivienda": str,
    "TransportePublicoVivienda": str,
    "IdProvincia": str,
    "Provincia": str,
    "domLocalidad": str,
    "domCalle": str,
    "domCalleAltura": str,
    "domPiso": str,
    "domDto": str,
    "domMunicipio": str,
    "domCodigoPostal": str,
    "IdMotivoRenuncia": str,
    "FechaFallecimiento": str,
    "MotivoOtro": str,
    "ADH_CUIL": str,
    "ADH_apeyNom": str,
    "ADH_Apellidos": str,
    "ADH_Nombres": str,
    "ADH_AdhiereObraSocial": str,
    "ADH_DatosAdp": str,
    "ADH_FechaNacimiento": str,
    "ADH_Sexo": str,
    "ADH_Edad": str,
    "ADH_IdCentroEducativo": str,
    "ADH_IdNivelEducativo": str,
    "ADH_NivelFinalizado": str,
    "ADH_ultimoAnioAprobado": str,
    "ADH_IngresoUltimos30Dias": str,
    "ADH_Ingresos": str,
    "ADH_IdParentesco": str,
}

dtypeDictSQL = {
    "IdSolicitud": sqlalchemy.types.VARCHAR(300),
    "IdTipoSolicitud": sqlalchemy.types.VARCHAR(300),
    "CUIL": sqlalchemy.types.VARCHAR(300),
    "CUILViejo": sqlalchemy.types.VARCHAR(300),
    "apeYnom": sqlalchemy.types.VARCHAR(300),
    "Apellidos": sqlalchemy.types.VARCHAR(300),
    "Nombres": sqlalchemy.types.VARCHAR(300),
    "FechaNacimiento": sqlalchemy.VARCHAR(300),
    "IdPaisNacimiento": sqlalchemy.types.VARCHAR(300),
    "Sexo": sqlalchemy.types.VARCHAR(300),
    "Edad": sqlalchemy.types.VARCHAR(300),
    "Telefono": sqlalchemy.types.VARCHAR(300),
    "Email": sqlalchemy.types.VARCHAR(300),
    "FechaUltAct": sqlalchemy.VARCHAR(300),
    "Dependencia": sqlalchemy.types.VARCHAR(300),
    "IdPrograma": sqlalchemy.types.VARCHAR(300),
    "IdTipoEfector": sqlalchemy.types.VARCHAR(300),
    "NombreAgrupamiento": sqlalchemy.types.VARCHAR(300),
    "Matricula": sqlalchemy.types.VARCHAR(300),
    "IdActividad": sqlalchemy.types.VARCHAR(300),
    "NumeroRenaf": sqlalchemy.types.VARCHAR(300),
    "IdCentroEducativo": sqlalchemy.types.VARCHAR(300),
    "IdNivelEducativo": sqlalchemy.types.VARCHAR(300),
    "NivelFinalizado": sqlalchemy.types.VARCHAR(300),
    "UltimoAnioAprobado": sqlalchemy.types.VARCHAR(300),
    "IdCoberturaSalud": sqlalchemy.types.VARCHAR(300),
    "IdAccesoSalud": sqlalchemy.types.VARCHAR(300),
    "IdDificultadSalud": sqlalchemy.types.VARCHAR(300),
    "IdObraSocial": sqlalchemy.types.VARCHAR(300),
    "IdTrabajoSemanaAnterior": sqlalchemy.types.VARCHAR(300),
    "TrabajoInformalSemanaAnterior": sqlalchemy.types.VARCHAR(300),
    "BuscoTrabajoUltimos30Dias": sqlalchemy.types.VARCHAR(300),
    "IdTiempoBuscaTrabajo": sqlalchemy.types.VARCHAR(300),
    "TrabajoAlgunaVez": sqlalchemy.types.VARCHAR(300),
    "IdTrabajoInformal": sqlalchemy.types.VARCHAR(300),
    "NombreTrabajoInformal": sqlalchemy.types.VARCHAR(300),
    "IdIngresosEfector": sqlalchemy.types.VARCHAR(300),
    "Ingresos": sqlalchemy.types.VARCHAR(300),
    "ComparteViviendaGrupoFamiliar": sqlalchemy.types.VARCHAR(300),
    "IdTipoVivienda": sqlalchemy.types.VARCHAR(300),
    "TipoViviendaOtro": sqlalchemy.types.VARCHAR(300),
    "IdMaterialPisoVivienda": sqlalchemy.types.VARCHAR(300),
    "IdMaterialTechoVivienda": sqlalchemy.types.VARCHAR(300),
    "AmbientesVivienda": sqlalchemy.types.VARCHAR(300),
    "IdAguaProvieneVivienda": sqlalchemy.types.VARCHAR(300),
    "IdAguaLlegaVivienda": sqlalchemy.types.VARCHAR(300),
    "IdBanioVivienda": sqlalchemy.types.VARCHAR(300),
    "IdDesagueVivienda": sqlalchemy.types.VARCHAR(300),
    "ZonaInundableVivienda": sqlalchemy.types.VARCHAR(300),
    "BasuralesVivienda": sqlalchemy.types.VARCHAR(300),
    "AlumbradoPublicoVivienda": sqlalchemy.types.VARCHAR(300),
    "PavimentoVivienda": sqlalchemy.types.VARCHAR(300),
    "RecoleccionResiduosVivienda": sqlalchemy.types.VARCHAR(300),
    "TransportePublicoVivienda": sqlalchemy.types.VARCHAR(300),
    "IdProvincia": sqlalchemy.types.VARCHAR(300),
    "Provincia": sqlalchemy.types.VARCHAR(300),
    "domLocalidad": sqlalchemy.types.VARCHAR(300),
    "domCalle": sqlalchemy.types.VARCHAR(300),
    "domCalleAltura": sqlalchemy.types.VARCHAR(300),
    "domPiso": sqlalchemy.types.VARCHAR(300),
    "domDto": sqlalchemy.types.VARCHAR(300),
    "domMunicipio": sqlalchemy.types.VARCHAR(300),
    "domCodigoPostal": sqlalchemy.types.VARCHAR(300),
    "IdMotivoRenuncia": sqlalchemy.types.VARCHAR(300),
    "FechaFallecimiento": sqlalchemy.VARCHAR(300),
    "MotivoOtro": sqlalchemy.types.VARCHAR(300),
    "ADH_CUIL": sqlalchemy.types.VARCHAR(300),
    "ADH_apeyNom": sqlalchemy.types.VARCHAR(300),
    "ADH_Apellidos": sqlalchemy.types.VARCHAR(300),
    "ADH_Nombres": sqlalchemy.types.VARCHAR(300),
    "ADH_AdhiereObraSocial": sqlalchemy.types.VARCHAR(300),
    "ADH_DatosAdp": sqlalchemy.types.VARCHAR(300),
    "ADH_FechaNacimiento": sqlalchemy.VARCHAR(300),
    "ADH_Sexo": sqlalchemy.types.VARCHAR(300),
    "ADH_Edad": sqlalchemy.types.VARCHAR(300),
    "ADH_IdCentroEducativo": sqlalchemy.types.VARCHAR(300),
    "ADH_IdNivelEducativo": sqlalchemy.types.VARCHAR(300),
    "ADH_NivelFinalizado": sqlalchemy.types.VARCHAR(300),
    "ADH_ultimoAnioAprobado": sqlalchemy.types.VARCHAR(300),
    "ADH_IngresoUltimos30Dias": sqlalchemy.types.VARCHAR(300),
    "ADH_Ingresos": sqlalchemy.types.VARCHAR(300),
    "ADH_IdParentesco": sqlalchemy.types.VARCHAR(300),
}

# SOMOSO 2.0 - namesList2 , dtypeDictCSV2, dtypeDictSQL2
namesList2 = [
    "IdSolicitud",
    "IdTipoSolicitud",
    "CUIL",
    "CUILViejo",
    "apeYnom",
    "Apellidos",
    "Nombres",
    "FechaNacimiento",
    "IdPaisNacimiento",
    "Sexo",
    "Edad",
    "Telefono",
    "Email",
    "FechaUltAct",
    "Dependencia",
    "IdPrograma",
    "IdTipoEfector",
    "NombreAgrupamiento",
    "Matricula",
    "IdActividad",
    "NumeroRenaf",
    "IdCentroEducativo",
    "IdNivelEducativo",
    "NivelFinalizado",
    "UltimoAnioAprobado",
    "IdCoberturaSalud",
    "IdAccesoSalud",
    "IdDificultadSalud",
    "IdObraSocial",
    "IdTrabajoSemanaAnterior",
    "TrabajoInformalSemanaAnterior",
    "BuscoTrabajoUltimos30Dias",
    "IdTiempoBuscaTrabajo",
    "TrabajoAlgunaVez",
    "IdTrabajoInformal",
    "NombreTrabajoInformal",
    "IdIngresosEfector",
    "Ingresos",
    "ComparteViviendaGrupoFamiliar",
    "IdTipoVivienda",
    "TipoViviendaOtro",
    "IdMaterialPisoVivienda",
    "IdMaterialTechoVivienda",
    "AmbientesVivienda",
    "IdAguaProvieneVivienda",
    "IdAguaLlegaVivienda",
    "IdBanioVivienda",
    "IdDesagueVivienda",
    "ZonaInundableVivienda",
    "BasuralesVivienda",
    "AlumbradoPublicoVivienda",
    "PavimentoVivienda",
    "RecoleccionResiduosVivienda",
    "TransportePublicoVivienda",
    "IdProvincia",
    "Provincia",
    "domLocalidad",
    "domCalle",
    "domCalleAltura",
    "domPiso",
    "domDto",
    "domMunicipio",
    "domCodigoPostal",
    "IdMotivoRenuncia",
    "FechaFallecimiento",
    "MotivoOtro",
    "ADH_CUIL",
    "ADH_apeyNom",
    "ADH_Apellidos",
    "ADH_Nombres",
    "ADH_AdhiereObraSocial",
    "ADH_DatosAdp",
    "ADH_FechaNacimiento",
    "ADH_Sexo",
    "ADH_Edad",
    "ADH_IdCentroEducativo",
    "ADH_IdNivelEducativo",
    "ADH_NivelFinalizado",
    "ADH_ultimoAnioAprobado",
    "ADH_IngresoUltimos30Dias",
    "ADH_Ingresos",
    "ADH_IdParentesco",
    "VersionModeloDatos",
    "TelefonoFijo",
    "TelefonoCelular",
    "IdGenero",
    "domDomTorre",
    "domDomBarrioParaje",
    "domManzana",
    "domDomCasa",
    "domDomDistritoDpto",
    "InicioActividades",
    "CantIntegrantes",
    "IdLugarActividad",
    "IdModalidadTrabajo",
    "IdMotivoInscripcion",
    "MotivoInscripcionOtros",
]

dtypeDictCSV2 = {
    "IdSolicitud": str,
    "IdTipoSolicitud": str,
    "CUIL": str,
    "CUILViejo": str,
    "apeYnom": str,
    "Apellidos": str,
    "Nombres": str,
    "FechaNacimiento": str,
    "IdPaisNacimiento": str,
    "Sexo": str,
    "Edad": str,
    "Telefono": str,
    "Email": str,
    "FechaUltAct": str,
    "Dependencia": str,
    "IdPrograma": str,
    "IdTipoEfector": str,
    "NombreAgrupamiento": str,
    "Matricula": str,
    "IdActividad": str,
    "NumeroRenaf": str,
    "IdCentroEducativo": str,
    "IdNivelEducativo": str,
    "NivelFinalizado": str,
    "UltimoAnioAprobado": str,
    "IdCoberturaSalud": str,
    "IdAccesoSalud": str,
    "IdDificultadSalud": str,
    "IdObraSocial": str,
    "IdTrabajoSemanaAnterior": str,
    "TrabajoInformalSemanaAnterior": str,
    "BuscoTrabajoUltimos30Dias": str,
    "IdTiempoBuscaTrabajo": str,
    "TrabajoAlgunaVez": str,
    "IdTrabajoInformal": str,
    "NombreTrabajoInformal": str,
    "IdIngresosEfector": str,
    "Ingresos": str,
    "ComparteViviendaGrupoFamiliar": str,
    "IdTipoVivienda": str,
    "TipoViviendaOtro": str,
    "IdMaterialPisoVivienda": str,
    "IdMaterialTechoVivienda": str,
    "AmbientesVivienda": str,
    "IdAguaProvieneVivienda": str,
    "IdAguaLlegaVivienda": str,
    "IdBanioVivienda": str,
    "IdDesagueVivienda": str,
    "ZonaInundableVivienda": str,
    "BasuralesVivienda": str,
    "AlumbradoPublicoVivienda": str,
    "PavimentoVivienda": str,
    "RecoleccionResiduosVivienda": str,
    "TransportePublicoVivienda": str,
    "IdProvincia": str,
    "Provincia": str,
    "domLocalidad": str,
    "domCalle": str,
    "domCalleAltura": str,
    "domPiso": str,
    "domDto": str,
    "domMunicipio": str,
    "domCodigoPostal": str,
    "IdMotivoRenuncia": str,
    "FechaFallecimiento": str,
    "MotivoOtro": str,
    "ADH_CUIL": str,
    "ADH_apeyNom": str,
    "ADH_Apellidos": str,
    "ADH_Nombres": str,
    "ADH_AdhiereObraSocial": str,
    "ADH_DatosAdp": str,
    "ADH_FechaNacimiento": str,
    "ADH_Sexo": str,
    "ADH_Edad": str,
    "ADH_IdCentroEducativo": str,
    "ADH_IdNivelEducativo": str,
    "ADH_NivelFinalizado": str,
    "ADH_ultimoAnioAprobado": str,
    "ADH_IngresoUltimos30Dias": str,
    "ADH_Ingresos": str,
    "ADH_IdParentesco": str,
    "VersionModeloDatos": str,
    "TelefonoFijo": str,
    "TelefonoCelular": str,
    "IdGenero": str,
    "domDomTorre": str,
    "domDomBarrioParaje": str,
    "domManzana": str,
    "domDomCasa": str,
    "domDomDistritoDpto": str,
    "InicioActividades": str,
    "CantIntegrantes": str,
    "IdLugarActividad": str,
    "IdModalidadTrabajo": str,
    "IdMotivoInscripcion": str,
    "MotivoInscripcionOtros": str,
}

dtypeDictSQL2 = {
    "IdSolicitud": sqlalchemy.types.VARCHAR(300),
    "IdTipoSolicitud": sqlalchemy.types.VARCHAR(300),
    "CUIL": sqlalchemy.types.VARCHAR(300),
    "CUILViejo": sqlalchemy.types.VARCHAR(300),
    "apeYnom": sqlalchemy.types.VARCHAR(300),
    "Apellidos": sqlalchemy.types.VARCHAR(300),
    "Nombres": sqlalchemy.types.VARCHAR(300),
    "FechaNacimiento": sqlalchemy.VARCHAR(300),
    "IdPaisNacimiento": sqlalchemy.types.VARCHAR(300),
    "Sexo": sqlalchemy.types.VARCHAR(300),
    "Edad": sqlalchemy.types.VARCHAR(300),
    "Telefono": sqlalchemy.types.VARCHAR(300),
    "Email": sqlalchemy.types.VARCHAR(300),
    "FechaUltAct": sqlalchemy.VARCHAR(300),
    "Dependencia": sqlalchemy.types.VARCHAR(300),
    "IdPrograma": sqlalchemy.types.VARCHAR(300),
    "IdTipoEfector": sqlalchemy.types.VARCHAR(300),
    "NombreAgrupamiento": sqlalchemy.types.VARCHAR(300),
    "Matricula": sqlalchemy.types.VARCHAR(300),
    "IdActividad": sqlalchemy.types.VARCHAR(300),
    "NumeroRenaf": sqlalchemy.types.VARCHAR(300),
    "IdCentroEducativo": sqlalchemy.types.VARCHAR(300),
    "IdNivelEducativo": sqlalchemy.types.VARCHAR(300),
    "NivelFinalizado": sqlalchemy.types.VARCHAR(300),
    "UltimoAnioAprobado": sqlalchemy.types.VARCHAR(300),
    "IdCoberturaSalud": sqlalchemy.types.VARCHAR(300),
    "IdAccesoSalud": sqlalchemy.types.VARCHAR(300),
    "IdDificultadSalud": sqlalchemy.types.VARCHAR(300),
    "IdObraSocial": sqlalchemy.types.VARCHAR(300),
    "IdTrabajoSemanaAnterior": sqlalchemy.types.VARCHAR(300),
    "TrabajoInformalSemanaAnterior": sqlalchemy.types.VARCHAR(300),
    "BuscoTrabajoUltimos30Dias": sqlalchemy.types.VARCHAR(300),
    "IdTiempoBuscaTrabajo": sqlalchemy.types.VARCHAR(300),
    "TrabajoAlgunaVez": sqlalchemy.types.VARCHAR(300),
    "IdTrabajoInformal": sqlalchemy.types.VARCHAR(300),
    "NombreTrabajoInformal": sqlalchemy.types.VARCHAR(300),
    "IdIngresosEfector": sqlalchemy.types.VARCHAR(300),
    "Ingresos": sqlalchemy.types.VARCHAR(300),
    "ComparteViviendaGrupoFamiliar": sqlalchemy.types.VARCHAR(300),
    "IdTipoVivienda": sqlalchemy.types.VARCHAR(300),
    "TipoViviendaOtro": sqlalchemy.types.VARCHAR(300),
    "IdMaterialPisoVivienda": sqlalchemy.types.VARCHAR(300),
    "IdMaterialTechoVivienda": sqlalchemy.types.VARCHAR(300),
    "AmbientesVivienda": sqlalchemy.types.VARCHAR(300),
    "IdAguaProvieneVivienda": sqlalchemy.types.VARCHAR(300),
    "IdAguaLlegaVivienda": sqlalchemy.types.VARCHAR(300),
    "IdBanioVivienda": sqlalchemy.types.VARCHAR(300),
    "IdDesagueVivienda": sqlalchemy.types.VARCHAR(300),
    "ZonaInundableVivienda": sqlalchemy.types.VARCHAR(300),
    "BasuralesVivienda": sqlalchemy.types.VARCHAR(300),
    "AlumbradoPublicoVivienda": sqlalchemy.types.VARCHAR(300),
    "PavimentoVivienda": sqlalchemy.types.VARCHAR(300),
    "RecoleccionResiduosVivienda": sqlalchemy.types.VARCHAR(300),
    "TransportePublicoVivienda": sqlalchemy.types.VARCHAR(300),
    "IdProvincia": sqlalchemy.types.VARCHAR(300),
    "Provincia": sqlalchemy.types.VARCHAR(300),
    "domLocalidad": sqlalchemy.types.VARCHAR(300),
    "domCalle": sqlalchemy.types.VARCHAR(300),
    "domCalleAltura": sqlalchemy.types.VARCHAR(300),
    "domPiso": sqlalchemy.types.VARCHAR(300),
    "domDto": sqlalchemy.types.VARCHAR(300),
    "domMunicipio": sqlalchemy.types.VARCHAR(300),
    "domCodigoPostal": sqlalchemy.types.VARCHAR(300),
    "IdMotivoRenuncia": sqlalchemy.types.VARCHAR(300),
    "FechaFallecimiento": sqlalchemy.VARCHAR(300),
    "MotivoOtro": sqlalchemy.types.VARCHAR(300),
    "ADH_CUIL": sqlalchemy.types.VARCHAR(300),
    "ADH_apeyNom": sqlalchemy.types.VARCHAR(300),
    "ADH_Apellidos": sqlalchemy.types.VARCHAR(300),
    "ADH_Nombres": sqlalchemy.types.VARCHAR(300),
    "ADH_AdhiereObraSocial": sqlalchemy.types.VARCHAR(300),
    "ADH_DatosAdp": sqlalchemy.types.VARCHAR(300),
    "ADH_FechaNacimiento": sqlalchemy.VARCHAR(300),
    "ADH_Sexo": sqlalchemy.types.VARCHAR(300),
    "ADH_Edad": sqlalchemy.types.VARCHAR(300),
    "ADH_IdCentroEducativo": sqlalchemy.types.VARCHAR(300),
    "ADH_IdNivelEducativo": sqlalchemy.types.VARCHAR(300),
    "ADH_NivelFinalizado": sqlalchemy.types.VARCHAR(300),
    "ADH_ultimoAnioAprobado": sqlalchemy.types.VARCHAR(300),
    "ADH_IngresoUltimos30Dias": sqlalchemy.types.VARCHAR(300),
    "ADH_Ingresos": sqlalchemy.types.VARCHAR(300),
    "ADH_IdParentesco": sqlalchemy.types.VARCHAR(300),
    "VersionModeloDatos": sqlalchemy.types.VARCHAR(300),
    "TelefonoFijo": sqlalchemy.types.VARCHAR(300),
    "TelefonoCelular": sqlalchemy.types.VARCHAR(300),
    "IdGenero": sqlalchemy.types.VARCHAR(300),
    "domDomTorre": sqlalchemy.types.VARCHAR(300),
    "domDomBarrioParaje": sqlalchemy.types.VARCHAR(300),
    "domManzana": sqlalchemy.types.VARCHAR(300),
    "domDomCasa": sqlalchemy.types.VARCHAR(300),
    "domDomDistritoDpto": sqlalchemy.types.VARCHAR(300),
    "InicioActividades": sqlalchemy.types.VARCHAR(300),
    "CantIntegrantes": sqlalchemy.types.VARCHAR(300),
    "IdLugarActividad": sqlalchemy.types.VARCHAR(300),
    "IdModalidadTrabajo": sqlalchemy.types.VARCHAR(300),
    "IdMotivoInscripcion": sqlalchemy.types.VARCHAR(300),
    "MotivoInscripcionOtros": sqlalchemy.types.VARCHAR(300),
}

# dicts para NOMS
dtypeDictNomsXLS = {
    "Apellidos": str,
    "Nombres": str,
    "TipoDoc": str,
    "NroDocumento": str,
    "Sexo": str,
    "FechaNacimiento": str,
    "Actividad": str,
    "Localidad": str,
    "Provincia": str,
    "Expediente": str,
    "Observaciones": str,
    "Operador": str,
}

dtypeDictNomsSQL = {
    "Apellidos": sqlalchemy.types.VARCHAR(100),
    "Nombres": sqlalchemy.types.VARCHAR(100),
    "TipoDoc": sqlalchemy.types.VARCHAR(100),
    "NroDocumento": sqlalchemy.types.VARCHAR(100),
    "Sexo": sqlalchemy.types.VARCHAR(100),
    "FechaNacimiento": sqlalchemy.types.VARCHAR(100),
    "Actividad": sqlalchemy.types.VARCHAR(100),
    "Localidad": sqlalchemy.types.VARCHAR(100),
    "Provincia": sqlalchemy.types.VARCHAR(100),
    "Expediente": sqlalchemy.types.VARCHAR(100),
    "Observaciones": sqlalchemy.types.VARCHAR(252),
    "Operador": sqlalchemy.types.VARCHAR(100),
}
