redlestips = (
    "Un cambio de adherentes puede tardar hasta 30 dias en impactar en la credencial AFIP.",
    "La fecha de baja en la AFIP es la fecha de baja del paquete 8.",
    "Monstruo Mercado les recuerda a sus clientes que los queremos mucho.",
    "Los miercoles a la tarde se procesan los paquetes de bajas y cambios de categoria.",
    "Los adherentes se procesan los jueves, solo si la vuelta del lote anterior esta impactada.",
    "Galleta de la fortuna : Alguien tirara mucho laburo en tu escritorio, de nuevo.",
    "Galleta de la fortuna : Tu sueldo se licuara con la inflación, de nuevo.",
    "Galleta de la fortuna : Lee este mensaje en voz alta y todos te oirán hablando sole.",
    "Galleta de la fortuna : Ayuda! Me tienen encerrado escribiendo estas cosas en una UDAI.",
    "Miren a ambos lados antes de cruzar.Sobretodo si es una peatonal.",
    "Si andan en bici vayan por la bicisenda.Si caminas no camines por la bicisenda.",
    "La proxima version va a traer stories.Nah mentira, nadie quiere ver tus fotos en Europa.",
    "La condescendencia no es maltrato, legalmente hablando.",
    "Si te gastaste todos tus 14-F anotate en un terciario y pedite dias de estudio.",
    "Si no estas seguro no apretes el botón, capo.",
    "Si bebiste, no uses Herramientas REDLES.",
    "MAXIMO ESFUERZO, MINIMO RESULTADO.",
    "Si no te gusta el modo darks, hace tu propia app y gana las elecciones.",
    "El desarrollador de esta app es cruel pero justo.", "NO COMPRES, ADOPTA.",
    "Los asociados no salen si la cooperativa no tiene expediente.",
    "Es mejor mandar un mail que hacer un llamado.",
    "RIP Enrique Lois. \n 2015-2019.")

redleshello = ("¿Ya pensaste que almorzar?", "¿Estas son horas de llegar?",
               "¿Ya firmaste la planilla?",
               "Espero hayas leido el mail con los cambios.",
               "Espero que hoy si labures, no como ayer.", "Te extrañe.",
               "Sos el unico que me cae bien.")