redlestips = (
    "Un cambio de adherentes puede tardar hasta 30 dias en impactar en la credencial AFIP.",
    "La fecha de baja en la AFIP es la fecha de baja del paquete 8.",
    "Los errores de obra social en la credencial AFIP(20072), se arreglan solos a la semana...usualmente.",
    "Monstruo Mercado les recuerda a sus clientes que los queremos mucho.",
    "Los miercoles a la tarde se procesan los paquetes de bajas y cambios de categoria.",
    "Los adherentes se procesan los jueves, solo si la vuelta del lote anterior esta impactada.",
    "Galleta de la fortuna : Alguien tirara mucho laburo en tu escritorio, de nuevo.",
    "Galleta de la fortuna : Tu sueldo se licuara con la inflación, de nuevo.",
    "Galleta de la fortuna : Lee este mensaje en voz alta y todos te oirán hablando sole.",
    "Galleta de la fortuna : Ayuda! Me tienen encerrado escribiendo estas cosas en una UDAI.",
    "Galleta de la fortuna : Alguien va a toser al lado tuyo apenas te saques el barbijo.",
    "Si estas leyendo esto, felicidades viniste a laburar.",
    "Arreglate el barbijo, se te bajo de nuevo.",
    "¿Y si esta semana te toca a vos? \n(El COVID, no el Telekino)",
    "Miren a ambos lados antes de cruzar.Sobretodo si es una peatonal.",
    "Si andan en bici vayan por la bicisenda.Si caminas no camines por la bicisenda.",
    "La proxima version va a traer stories.Nah mentira, nadie quiere ver tus fotos en Europa.",
    "La condescendencia no es maltrato, legalmente hablando.",
    "Si te gastaste todos tus 14-F anotate en un terciario y pedite dias de estudio, o agarrate COVID.",
    "Si no estas seguro no apretes el botón, capo.",
    "Si bebiste, no uses SUPER Herramientas REDLES.",
    "El SUPER es marketinero.",
    "MAXIMO ESFUERZO, MINIMO RESULTADO.",
    "Si no te gusta el modo darks, hace tu propia app y gana las elecciones.",
    "El desarrollador de esta app es cruel pero justo.",
    "NO COMPRES, ADOPTA.",
    "Los asociados no salen en P4 si su cooperativa no tiene expediente (Por mas que esten evaluados positivos).",
    "Es mejor mandar un mail que hacer un llamado.",
    "RIP Enrique Lois. \n 2015-2019.",
    "Si te cruzas con Eze recordale tu nombre, no se acuerda.",
)

redleshello = (
    "¿Ya pensaste que almorzar?",
    "¿Estas son horas de llegar?",
    "¿Ya firmaste la planilla?",
    "Mejor que tengas puesto el barbijo.",
    "¿Ya te lavaste las manos?",
    "Espero hayas leido el mail con los cambios.",
    "Espero que hoy si labures, no como ayer.",
    "Te extrañe.",
    "Sos el unico que me cae bien.",
)
